name: OpenWrt Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          build-essential \
          libncurses5-dev \
          zlib1g-dev \
          gawk \
          git \
          ccache \
          gettext \
          libssl-dev \
          xsltproc \
          wget
      - name: Prepare OpenWrt Environment
        run: |
          git clone https://github.com/openwrt/openwrt.git
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
      - name: Customize OpenWrt
        run: |
          # Your customization scripts go here
      - name: Build OpenWrt
        run: |
          cd openwrt
          make -j$(nproc) download
          make -j$(nproc) V=s
